listen=":8080"
user_api="http://127.0.0.1:8080"
[dbservers]
    [dbserver.testdb]
        host="127.0.0.1"
        port=8400
        dbname="my_test"
        user="root"
        password="bhjRjxwC8EBqaJC7"
